/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JTextArea;

public class RoomCRUD extends javax.swing.JFrame {

    /**
     * Creates new form RoomCRUD
     */
    Connection con;
    Statement st;
    ArrayList<Room> rooms = new ArrayList<>();

    public RoomCRUD() {
    	getContentPane().setBackground(Color.WHITE);
        initComponents();
        fetch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHotelID = new javax.swing.JTextField();
        jLabelHotelID = new javax.swing.JLabel();
        jLabelDesc = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRooms = new javax.swing.JTable();
        tblRooms.setBackground(Color.WHITE);
        btnSave = new javax.swing.JButton();
        btnSave.setBackground(new Color(240, 230, 140));
        btnUpdate = new javax.swing.JButton();
        btnUpdate.setBackground(new Color(240, 230, 140));
        btnDelete1 = new javax.swing.JButton();
        btnDelete1.setBackground(new Color(240, 230, 140));
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ROOM");

        jLabelHotelID.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelHotelID.setText("Hotel ID");

        jLabelDesc.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDesc.setText("Description");

        tblRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
            		"Room ID","Hotel ID","Price", "Type", "Description", "Day", "Month", "Year", "IsAvailable"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRooms.setCellSelectionEnabled(true);
        tblRooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRoomsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRooms);
        if (tblRooms.getColumnModel().getColumnCount() > 0) {
            tblRooms.getColumnModel().getColumn(2).setResizable(false);
        }

        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.setIconTextGap(0);
        btnSave.setInheritsPopupMenu(true);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete1.setText("Delete");
        btnDelete1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ROOM CRUD APPLICATION");
        
        String t1[] = { "Dog", "Cat"};       
        comboBox_Type = new JComboBox(t1);
        comboBox_Type.setBackground(new Color(240, 128, 128));
        
        lblType = new JLabel("Type");
        lblType.setFont(new Font("Verdana", Font.PLAIN, 12));
        
        String r1[] = { "true", "false"}; 
        comboBox_IsAvailable = new JComboBox(r1);
        comboBox_IsAvailable.setBackground(new Color(255, 160, 122));
        
        lblIsAvailable = new JLabel("Is Available");
        lblIsAvailable.setFont(new Font("Verdana", Font.PLAIN, 12));
        
        textDay = new JTextField();
        textDay.setColumns(10);
        
        lblDay = new JLabel("Day");
        lblDay.setFont(new Font("Verdana", Font.PLAIN, 12));
        
        textMonth = new JTextField();
        textMonth.setColumns(10);
        
        textYear = new JTextField();
        textYear.setColumns(10);
        
        lblMonth = new JLabel("Month");
        lblMonth.setFont(new Font("Verdana", Font.PLAIN, 12));
        
        lblYear = new JLabel("Year");
        lblYear.setFont(new Font("Verdana", Font.PLAIN, 12));
        
        textRoomID = new JTextField();
        textRoomID.setColumns(10);
        
        lblRoomID = new JLabel("Room ID");
        lblRoomID.setFont(new Font("Verdana", Font.PLAIN, 12));
        
        textPrice = new JTextField();
        textPrice.setColumns(10);
        
        JLabel lblPrice = new JLabel("Price");
        lblPrice.setFont(new Font("Verdana", Font.PLAIN, 12));
        
        btnNewButton = new JButton("BACK");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
				MenuAdminPage mp = new MenuAdminPage();
				mp.getFrame().setVisible(true);
				setVisible(false);
        	}
        });
        btnNewButton.setBackground(new Color(0, 128, 128));
        btnNewButton.setFont(new Font("Verdana", Font.PLAIN, 14));
        
        JTextArea textArea = new JTextArea();
		textArea.setBounds(27, 351, 193, 216);		
		//Get the only object available
		Room object = Room.getInstance();		
		String str=object.showMessage();
		textArea.append(str);
		getContentPane().add(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(133)
        							.addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 119, GroupLayout.PREFERRED_SIZE)
        							.addGap(72)
        							.addComponent(btnUpdate, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE)
        							.addGap(61)
        							.addComponent(btnDelete1, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
        							.addGap(95))
        						.addGroup(layout.createSequentialGroup()
        							.addContainerGap(124, Short.MAX_VALUE)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        								.addGroup(layout.createSequentialGroup()
        									.addGroup(layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(lblIsAvailable, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
        										.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        											.addComponent(lblType, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE)
        											.addComponent(jLabelDesc, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE))
        										.addComponent(lblPrice, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE))
        									.addPreferredGap(ComponentPlacement.RELATED))
        								.addGroup(layout.createSequentialGroup()
        									.addGroup(layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(lblRoomID, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        										.addComponent(jLabelHotelID, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE))
        									.addGap(34)))
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(textPrice, Alignment.LEADING, 200, 200, 200)
        								.addComponent(comboBox_IsAvailable, 0, 200, Short.MAX_VALUE)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(comboBox_Type, 0, 200, Short.MAX_VALUE)
        									.addPreferredGap(ComponentPlacement.RELATED))
        								.addComponent(txtDescription, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        								.addGroup(layout.createSequentialGroup()
        									.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        										.addComponent(textRoomID, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        										.addComponent(txtHotelID, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        									.addPreferredGap(ComponentPlacement.RELATED)))
        							.addPreferredGap(ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        									.addComponent(textMonth)
        									.addComponent(textYear, GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        									.addComponent(lblMonth, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        									.addComponent(lblYear, GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        									.addComponent(textDay, GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        									.addComponent(lblDay, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(textArea, GroupLayout.PREFERRED_SIZE, 166, GroupLayout.PREFERRED_SIZE)
        									.addGap(12)))))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 778, GroupLayout.PREFERRED_SIZE)
        					.addGap(145))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(242)
        					.addComponent(jLabel4)))
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(1465, Short.MAX_VALUE)
        			.addComponent(btnNewButton)
        			.addGap(99))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addGap(106)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textRoomID, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblRoomID))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(20)
        					.addComponent(lblDay)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(textDay, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(lblMonth)
        					.addGap(13)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(comboBox_Type, GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        						.addComponent(lblType, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        						.addComponent(textMonth, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
        					.addGap(18))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(txtHotelID, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabelHotelID, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
        					.addGap(88)))
        			.addGap(8)
        			.addComponent(lblYear)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtDescription, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabelDesc, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(textYear, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(comboBox_IsAvailable, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblIsAvailable))
        					.addGap(39)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(textPrice, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblPrice))
        					.addGap(78))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(76)
        					.addComponent(textArea, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnUpdate, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnDelete1, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(61, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(82)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 579, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
        			.addComponent(btnNewButton))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    	String room_id = textRoomID.getText().trim();
        String hotel_id = txtHotelID.getText().trim();
        String price = textPrice.getText().trim();
        String type=comboBox_Type.getEditor().getItem().toString();
        String descr = txtDescription.getText().trim();     
        String day = textDay.getText().trim();
        String month = textMonth.getText().trim();
        String year = textYear.getText().trim();
        String isAvailable=comboBox_IsAvailable.getEditor().getItem().toString();
        
        if (!room_id.isEmpty() && !hotel_id.isEmpty() && !price.isEmpty() && !type.isEmpty() && !descr.isEmpty()&& !day.isEmpty() && !month.isEmpty() && !year.isEmpty()&& !isAvailable.isEmpty()  ) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pet_hotel", "root", "");
                String sql = "select * from room where room_id='" + room_id + "'";
                st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                if (!rs.first()) {
                    saveHotel(room_id,hotel_id,price,type,descr,day,month,year,isAvailable);
                    DefaultTableModel model = (DefaultTableModel) tblRooms.getModel();
                    Object[] row = new Object[9];
                    row[0] = room_id;
                    row[1] = hotel_id;
                    row[2] = price; 
                    row[3] = type; 
                    row[4] = descr;                     
                    row[5] = day; 
                    row[6] = month; 
                    row[7] = year;
                    row[8] = isAvailable;
                    model.addRow(row);
                } else {
                    alert("Please provide a different id number", "Similar id found");
                }

                clear();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(HotelCRUD.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    con.close();
                    st.close();
                } catch (SQLException ex) {
                    Logger.getLogger(HotelCRUD.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } //        else if (!id.matches("^[0-9]{8}$")) {
        //            alert("please provide a valid id number", "Wrong id");
        //        } 
        else {
            alert("please fill in all the details");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    	String room_id = textRoomID.getText().trim();
        String hotel_id = txtHotelID.getText().trim();
        String price = textPrice.getText().trim();
        String type=comboBox_Type.getEditor().getItem().toString();
        String descr = txtDescription.getText().trim();     
        String day = textDay.getText().trim();
        String month = textMonth.getText().trim();
        String year = textYear.getText().trim();
        String isAvailable=comboBox_IsAvailable.getEditor().getItem().toString();
        
        if (!room_id.isEmpty() && !hotel_id.isEmpty() && !price.isEmpty() && !type.isEmpty() && !descr.isEmpty()&& !day.isEmpty() && !month.isEmpty() && !year.isEmpty()&& !isAvailable.isEmpty()  ) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pet_hotel", "root", "");
                String sql = "select * from room where room_id='" + room_id + "'";
                st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                if (rs.first()) {
                    update(room_id,hotel_id,price,type,descr,day,month,year,isAvailable);
                    DefaultTableModel model = (DefaultTableModel) tblRooms.getModel();
                    model.setRowCount(0);                   
                    fetch();
                    alert("Update was successful");
                    
                } else {
                    alert("There is no such room", "Update error");
                    clear();
                }

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(HotelCRUD.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            alert("There is nothing to update :(","No row selected");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    //set the values of a row to the textfields
    private void tblRoomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRoomsMouseClicked
        // TODO add your handling code here:
        int i = tblRooms.getSelectedRow();
        TableModel model = tblRooms.getModel();
        textRoomID.setText(model.getValueAt(i, 0).toString());
        txtHotelID.setText(model.getValueAt(i, 1).toString());
        textPrice.setText(model.getValueAt(i, 2).toString());
        comboBox_Type.getEditor().setItem(model.getValueAt(i, 3).toString());
        txtDescription.setText(model.getValueAt(i, 4).toString());     
        textDay.setText(model.getValueAt(i, 5).toString());
        textMonth.setText(model.getValueAt(i, 6).toString());
        textYear.setText(model.getValueAt(i, 7).toString());
        comboBox_IsAvailable.getEditor().setItem(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_tblRoomsMouseClicked

    //handles delete button action
    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        int i = tblRooms.getSelectedRow();
        if (i >= 0) {
            int option = JOptionPane.showConfirmDialog(rootPane,
                    "Are you sure you want to Delete?", "Delete confirmation", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                TableModel model = tblRooms.getModel();

                String id = model.getValueAt(i, 0).toString();
                if (tblRooms.getSelectedRows().length == 1) {
                    delete(id);
                    DefaultTableModel model1 = (DefaultTableModel) tblRooms.getModel();
                    model1.setRowCount(0);
                    fetch();
                    clear();
                }
            }
        } else {
            alert("Please select a row to delete");
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    //method to show an info alert
    public void alert(String msg) {
        JOptionPane.showMessageDialog(rootPane, msg);
    }

    //method to show an error alert
    public void alert(String msg, String title) {
        JOptionPane.showMessageDialog(rootPane, msg, title, JOptionPane.ERROR_MESSAGE);
    }
  
    //method to save room to the db
    public void saveHotel(String room_id, String hotel_id, String price, String type,String descr,String day,String month,String year,String isAvailable) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pet_hotel", "root", "");
            String sql = "INSERT INTO `room`(`room_id`, `hotel_id`, `price`, `type`,`descr`, `day`,`month`, `year`, `isAvailable`) "
                    + "VALUES ('" + room_id + "','" + hotel_id + "','" + price + "','" + type + "','" + descr + "','" + day + "','" + month + "','" + year + "','" + isAvailable + "')";
            st = con.createStatement();
            st.execute(sql);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(HotelCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
//        fetch();
    }

    //update the db
    public void update(String room_id, String hotel_id, String price, String type,String descr,String day,String month,String year,String isAvailable) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pet_hotel", "root", "");
            String sql = "UPDATE `room`SET hotel_id='" + hotel_id+ "',price='" + price  + "',type='" + type + "',descr='" + descr + "',day='" + day + 
            		                     "',month='" + month + "',year='" + year + "',isAvailable='" + isAvailable + "'WHERE room_id='" + room_id + "'";
            st = con.createStatement();
            st.execute(sql);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(HotelCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
//        fetch();
    }

    //delete details in the db
    public void delete(String id) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pet_hotel", "root", "");
            String sql = "DELETE FROM `room` WHERE room_id='" + id + "'";
            st = con.createStatement();
            st.execute(sql);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(HotelCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
//        fetch();
    }

    //method to clear the txt fields
    private void clear() {
        textRoomID.setText("");
        txtHotelID.setText("");
        textPrice.setText("");
        comboBox_Type.getEditor().setItem("");
        txtDescription.setText("");      
        textDay.setText("");
        textMonth.setText("");
        textYear.setText("");
        comboBox_IsAvailable.getEditor().setItem("");
    }

    //fetch 
    private void fetch() {
        rooms.clear();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pet_hotel", "root", "");
            String sql = "select * from room";
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
            	Date date=new Date(rs.getString("day"), rs.getString("month"), rs.getString("year"),Boolean.parseBoolean( rs.getString("isAvailable")));
                Room room = new Room(Integer.parseInt(rs.getString("room_id")),Integer.parseInt( rs.getString("hotel_id")),Integer.parseInt( rs.getString("price")), rs.getString("type"),rs.getString("descr"), 
                		date);
                rooms.add(room);
            }
            DefaultTableModel model = (DefaultTableModel) tblRooms.getModel();
            for (Room room: rooms) {

                Object[] row = new Object[9];
                row[0] = room.getRoom_id();
                row[1] = room.getRoom_hotel_id();
                row[2] = room.getRoom_price();
                row[3] = room.getRoom_type();
                row[4] = room.getRoom_description();
                row[5] = room.getDate().getDay();
                row[6] = room.getDate().getMonth();
                row[7] = room.getDate().getYear();
                row[8] = room.getDate().isAvailable();

                model.addRow(row);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RoomCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RoomCRUD().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabelHotelID;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRooms;
    private javax.swing.JTextField txtHotelID;
    private javax.swing.JTextField txtDescription;
    private JComboBox comboBox_IsAvailable;
    private JComboBox comboBox_Type;
    private JLabel lblIsAvailable;
    private JTextField textDay;
    private JLabel lblDay;
    private JTextField textMonth;
    private JTextField textYear;
    private JLabel lblMonth;
    private JLabel lblYear;
    private JLabel lblType;
    private JTextField textRoomID;
    private JLabel lblRoomID;
    private JTextField textPrice;
    private JButton btnNewButton;
}
